// <auto-generated />
using System;
using GamesInfoSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesInfoSys.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GamesInfoSys.Data.Entities.OfferPricePoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginalPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoreOfferId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreOfferId", "AtUtc");

                    b.ToTable("OfferPricePoints");
                });

            modelBuilder.Entity("GamesInfoSys.Data.Entities.StoreOffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginalPriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PriceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackedGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Store", "ExternalId", "Region")
                        .IsUnique();

                    b.HasIndex("TrackedGameId", "Platform", "Region");

                    b.ToTable("StoreOffers");
                });

            modelBuilder.Entity("GamesInfoSys.Data.Entities.TrackedGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicOfferId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GogProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NintendoProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PsnProductId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RawgGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamAppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("XboxProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RawgGameId");

                    b.ToTable("TrackedGames");
                });

            modelBuilder.Entity("GamesInfoSys.Data.Entities.OfferPricePoint", b =>
                {
                    b.HasOne("GamesInfoSys.Data.Entities.StoreOffer", "StoreOffer")
                        .WithMany()
                        .HasForeignKey("StoreOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreOffer");
                });

            modelBuilder.Entity("GamesInfoSys.Data.Entities.StoreOffer", b =>
                {
                    b.HasOne("GamesInfoSys.Data.Entities.TrackedGame", "TrackedGame")
                        .WithMany()
                        .HasForeignKey("TrackedGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedGame");
                });
#pragma warning restore 612, 618
        }
    }
}
