using System.Globalization;

namespace GamesInfoSys.Services;

public sealed class UiText
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["SiteName"] = "GamesInfoSys",
        ["NavHome"] = "Home",
        ["NavBrowse"] = "Browse",
        ["NavPrivacy"] = "Privacy",
        ["Language"] = "Language",
        ["LangEnglish"] = "English",
        ["LangUkrainian"] = "Ukrainian",
        ["FooterPrivacy"] = "Privacy",
        ["HomeTitle"] = "Home",
        ["HeroTitle"] = "Game Info Aggregator",
        ["HeroText"] = "Search and browse games, open details, and keep everything in one place.",
        ["BrowseGames"] = "Browse games",
        ["FastSearch"] = "Fast search",
        ["FastSearchText"] = "Type a title and jump straight to a game page.",
        ["DemoMode"] = "Demo mode",
        ["DemoModeText"] = "Works without API keys; add a RAWG key later for live data.",
        ["PrivacyTitle"] = "Privacy Policy",
        ["PrivacyLead"] = "This site does not require accounts and does not intentionally collect personal data.",
        ["PrivacyItem1"] = "When configured with a RAWG API key, the server requests game metadata from RAWG and shows it in the UI.",
        ["PrivacyItem2"] = "In demo mode (no API key), the site uses a small local dataset.",
        ["PrivacyItem3"] = "Links to external sites (official game websites, images) may have their own privacy practices.",
        ["BrowseTitle"] = "Browse",
        ["BrowseHeading"] = "Browse games",
        ["Live"] = "Live",
        ["DataViaRawg"] = "Data via RAWG.",
        ["SetRawgApiKey"] = "Set Rawg:ApiKey to fetch live data.",
        ["SearchPlaceholder"] = "Search (e.g. Elden Ring)",
        ["Search"] = "Search",
        ["TipTopGames"] = "Tip: leave empty for top games.",
        ["Clear"] = "Clear",
        ["NoGamesFound"] = "No games found.",
        ["CoverAlt"] = "cover",
        ["GameTitleFallback"] = "Game",
        ["GameNotFound"] = "Game not found.",
        ["Back"] = "Back",
        ["Released"] = "Released",
        ["Metacritic"] = "Metacritic",
        ["Rating"] = "Rating",
        ["OfficialWebsite"] = "Official website",
        ["BackToBrowse"] = "Back to browse",
        ["PricesHeading"] = "Prices (Region: UA, Switch: ZA)",
        ["PricesSubheading"] = "Official stores and marketplaces. Add identifiers to enable more platforms.",
        ["BrowseButton"] = "Browse",
        ["DemoModeNote"] = "Demo mode note: store buttons below come from the demo JSON (not live platform APIs).",
        ["OpenStore"] = "Open {0}",
        ["BestMarketplaceDeal"] = "Best marketplace deal:",
        ["Open"] = "Open",
        ["NoOffers"] = "No offers yet. If RAWG provides a Steam link it will be detected automatically; otherwise add a Steam App ID below.",
        ["Platform"] = "Platform",
        ["Store"] = "Store",
        ["Region"] = "Region",
        ["Price"] = "Price",
        ["Marketplace"] = "Marketplace",
        ["OpenDeal"] = "Open deal",
        ["SteamMappingOptional"] = "Steam mapping (optional)",
        ["AddOrChange"] = "Add / change",
        ["SteamLinkOrAppId"] = "Steam link or App ID",
        ["SteamInputPlaceholder"] = "https://store.steampowered.com/app/1245620/  or  1245620",
        ["SteamTip"] = "Tip: open Steam in browser and copy the URL.",
        ["SteamValidation"] = "Paste a Steam app link or an App ID.",
        ["SaveRefresh"] = "Save & refresh",
        ["About"] = "About",
        ["NoDescription"] = "No description available.",
        ["FindInUkraine"] = "Find in Ukraine",
        ["FindInUkraineText"] = "Quick searches for physical copies or gift cards. Prices may differ by edition/platform.",
        ["CheapSharkDeals"] = "CheapShark deals",
        ["PsStoreOfficial"] = "PS Store (official)",
        ["XboxStoreOfficial"] = "Xbox Store (official)",
        ["NintendoStoreOfficial"] = "Nintendo eShop ZA (official)",
        ["YouTubeReview"] = "YouTube review",
        ["YouTubeGameplay"] = "YouTube gameplay",
        ["PlatformSearches"] = "Platform searches",
        ["PromPs"] = "Prom (PS)",
        ["OlxPs"] = "OLX (PS)",
        ["RozetkaPs"] = "Rozetka (PS)",
        ["PromXbox"] = "Prom (Xbox)",
        ["OlxXbox"] = "OLX (Xbox)",
        ["RozetkaXbox"] = "Rozetka (Xbox)",
        ["PromSwitch"] = "Prom (Switch)",
        ["OlxSwitch"] = "OLX (Switch)",
        ["RozetkaSwitch"] = "Rozetka (Switch)",
        ["Genres"] = "Genres",
        ["Platforms"] = "Platforms",
        ["Screenshots"] = "Screenshots",
        ["ScreenshotAlt"] = "Screenshot",
        ["ErrorTitle"] = "Error",
        ["ErrorHeading"] = "Error.",
        ["ErrorText"] = "An error occurred while processing your request.",
        ["RequestId"] = "Request ID:",
        ["DevelopmentMode"] = "Development Mode",
        ["DevelopmentModeText1"] = "Swapping to the Development environment displays detailed information about the error that occurred.",
        ["DevelopmentModeText2"] = "The Development environment shouldn't be enabled for deployed applications.",
        ["DevelopmentModeText3"] = "It can result in displaying sensitive information from exceptions to end users.",
        ["DevelopmentModeText4"] = "For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app."
    };

    private static readonly IReadOnlyDictionary<string, string> Ukrainian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["SiteName"] = "GamesInfoSys",
        ["NavHome"] = "Головна",
        ["NavBrowse"] = "Каталог",
        ["NavPrivacy"] = "Конфіденційність",
        ["Language"] = "Мова",
        ["LangEnglish"] = "Англійська",
        ["LangUkrainian"] = "Українська",
        ["FooterPrivacy"] = "Конфіденційність",
        ["HomeTitle"] = "Головна",
        ["HeroTitle"] = "Агрегатор ігор",
        ["HeroText"] = "Шукайте ігри, переглядайте каталог, відкривайте деталі та тримайте все в одному місці.",
        ["BrowseGames"] = "Переглянути ігри",
        ["FastSearch"] = "Швидкий пошук",
        ["FastSearchText"] = "Введіть назву і швидко перейдіть на сторінку гри.",
        ["DemoMode"] = "Демо-режим",
        ["DemoModeText"] = "Працює без API-ключів; для живих даних можна пізніше додати ключ RAWG.",
        ["PrivacyTitle"] = "Політика конфіденційності",
        ["PrivacyLead"] = "Сайт не вимагає облікових записів і навмисно не збирає персональні дані.",
        ["PrivacyItem1"] = "Коли налаштовано ключ RAWG API, сервер запитує метадані ігор у RAWG і показує їх в інтерфейсі.",
        ["PrivacyItem2"] = "У демо-режимі (без API-ключа) сайт використовує невеликий локальний набір даних.",
        ["PrivacyItem3"] = "Посилання на зовнішні сайти (офіційні сайти ігор, зображення) можуть мати власні правила конфіденційності.",
        ["BrowseTitle"] = "Каталог",
        ["BrowseHeading"] = "Перегляд ігор",
        ["Live"] = "Наживо",
        ["DataViaRawg"] = "Дані через RAWG.",
        ["SetRawgApiKey"] = "Вкажіть Rawg:ApiKey, щоб отримувати живі дані.",
        ["SearchPlaceholder"] = "Пошук (наприклад, Elden Ring)",
        ["Search"] = "Пошук",
        ["TipTopGames"] = "Порада: залиште поле порожнім, щоб побачити топ ігор.",
        ["Clear"] = "Очистити",
        ["NoGamesFound"] = "Ігор не знайдено.",
        ["CoverAlt"] = "обкладинка",
        ["GameTitleFallback"] = "Гра",
        ["GameNotFound"] = "Гру не знайдено.",
        ["Back"] = "Назад",
        ["Released"] = "Реліз",
        ["Metacritic"] = "Metacritic",
        ["Rating"] = "Рейтинг",
        ["OfficialWebsite"] = "Офіційний сайт",
        ["BackToBrowse"] = "Назад до каталогу",
        ["PricesHeading"] = "Ціни (Регіон: UA, Switch: ZA)",
        ["PricesSubheading"] = "Офіційні магазини та маркетплейси. Додайте ідентифікатори, щоб увімкнути більше платформ.",
        ["BrowseButton"] = "Каталог",
        ["DemoModeNote"] = "Примітка демо-режиму: кнопки магазинів нижче беруться з demo JSON, а не з живих API платформ.",
        ["OpenStore"] = "Відкрити {0}",
        ["BestMarketplaceDeal"] = "Найкраща пропозиція маркетплейсу:",
        ["Open"] = "Відкрити",
        ["NoOffers"] = "Пропозицій поки немає. Якщо RAWG надає Steam-посилання, воно буде визначене автоматично; інакше додайте Steam App ID нижче.",
        ["Platform"] = "Платформа",
        ["Store"] = "Магазин",
        ["Region"] = "Регіон",
        ["Price"] = "Ціна",
        ["Marketplace"] = "Маркетплейс",
        ["OpenDeal"] = "Відкрити пропозицію",
        ["SteamMappingOptional"] = "Steam-зв'язка (необов'язково)",
        ["AddOrChange"] = "Додати / змінити",
        ["SteamLinkOrAppId"] = "Steam-посилання або App ID",
        ["SteamInputPlaceholder"] = "https://store.steampowered.com/app/1245620/  або  1245620",
        ["SteamTip"] = "Порада: відкрийте Steam у браузері та скопіюйте URL.",
        ["SteamValidation"] = "Вставте Steam-посилання або App ID.",
        ["SaveRefresh"] = "Зберегти й оновити",
        ["About"] = "Про гру",
        ["NoDescription"] = "Опис недоступний.",
        ["FindInUkraine"] = "Пошук в Україні",
        ["FindInUkraineText"] = "Швидкі пошуки фізичних копій або подарункових карток. Ціни можуть відрізнятися залежно від видання та платформи.",
        ["CheapSharkDeals"] = "Пропозиції CheapShark",
        ["PsStoreOfficial"] = "PS Store (офіційно)",
        ["XboxStoreOfficial"] = "Xbox Store (офіційно)",
        ["NintendoStoreOfficial"] = "Nintendo eShop ZA (офіційно)",
        ["YouTubeReview"] = "Огляд на YouTube",
        ["YouTubeGameplay"] = "Геймплей на YouTube",
        ["PlatformSearches"] = "Пошук за платформами",
        ["PromPs"] = "Prom (PS)",
        ["OlxPs"] = "OLX (PS)",
        ["RozetkaPs"] = "Rozetka (PS)",
        ["PromXbox"] = "Prom (Xbox)",
        ["OlxXbox"] = "OLX (Xbox)",
        ["RozetkaXbox"] = "Rozetka (Xbox)",
        ["PromSwitch"] = "Prom (Switch)",
        ["OlxSwitch"] = "OLX (Switch)",
        ["RozetkaSwitch"] = "Rozetka (Switch)",
        ["Genres"] = "Жанри",
        ["Platforms"] = "Платформи",
        ["Screenshots"] = "Скріншоти",
        ["ScreenshotAlt"] = "Скріншот",
        ["ErrorTitle"] = "Помилка",
        ["ErrorHeading"] = "Помилка.",
        ["ErrorText"] = "Під час обробки вашого запиту сталася помилка.",
        ["RequestId"] = "ID запиту:",
        ["DevelopmentMode"] = "Режим розробки",
        ["DevelopmentModeText1"] = "Перехід у середовище Development показує детальну інформацію про помилку.",
        ["DevelopmentModeText2"] = "Середовище Development не слід вмикати на розгорнутих застосунках.",
        ["DevelopmentModeText3"] = "Це може призвести до показу чутливої інформації з винятків кінцевим користувачам.",
        ["DevelopmentModeText4"] = "Для локального налагодження увімкніть середовище Development, встановивши змінну ASPNETCORE_ENVIRONMENT у значення Development, а потім перезапустіть застосунок."
    };

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        var texts = IsUkrainian() ? Ukrainian : English;
        return texts.TryGetValue(key, out var value)
            ? value
            : English.TryGetValue(key, out var fallback)
                ? fallback
                : key;
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentUICulture, Get(key), args);
    }

    private static bool IsUkrainian()
    {
        return string.Equals(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName, "uk", StringComparison.OrdinalIgnoreCase);
    }
}
